echo 1; figlet -f 1row.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 2; figlet -f 3d_diagonal.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 3; figlet -f 3-d.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 4; figlet -f 3x5.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 5; figlet -f 4max.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 6; figlet -f 5lineoblique.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 7; figlet -f acrobatic.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 8; figlet -f alligator2.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 9; figlet -f alligator3.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 10; figlet -f alligator.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 11; figlet -f alphabet.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 12; figlet -f alpha.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 13; figlet -f amc3line.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 14; figlet -f amc3liv1.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 15; figlet -f amcaaa01.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 16; figlet -f amcneko.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 17; figlet -f amcrazo2.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 18; figlet -f amcrazor.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 19; figlet -f amcslash.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 20; figlet -f amcslder.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 21; figlet -f amcthin.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 22; figlet -f amctubes.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 23; figlet -f amcun1.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 24; figlet -f arrows.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 25; figlet -f ascii_new_roman.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 26; figlet -f avatar.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 27; figlet -f B1FF.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 28; figlet -f banner3-D.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 29; figlet -f banner3.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 30; figlet -f banner4.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 31; figlet -f banner.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 32; figlet -f barbwire.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 33; figlet -f basic.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 34; figlet -f bear.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 35; figlet -f bell.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 36; figlet -f benjamin.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 37; figlet -f bigchief.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 38; figlet -f bigfig.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 39; figlet -f big.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 40; figlet -f binary.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 41; figlet -f block.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 42; figlet -f blocks.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 43; figlet -f bolger.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 44; figlet -f braced.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 45; figlet -f bright.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 46; figlet -f broadway.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 47; figlet -f broadway_kb.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 48; figlet -f bubble.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 49; figlet -f bulbhead.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 50; figlet -f calgphy2.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 51; figlet -f caligraphy.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 52; figlet -f cards.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 53; figlet -f catwalk.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 54; figlet -f chiseled.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 55; figlet -f chunky.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 56; figlet -f coinstak.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 57; figlet -f cola.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 58; figlet -f colossal.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 59; figlet -f computer.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 60; figlet -f contessa.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 61; figlet -f contrast.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 62; figlet -f cosmic.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 63; figlet -f cosmike.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 64; figlet -f crawford.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 65; figlet -f crazy.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 66; figlet -f cricket.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 67; figlet -f cyberlarge.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 68; figlet -f cybermedium.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 69; figlet -f cybersmall.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 70; figlet -f cygnet.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 71; figlet -f DANC4.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 72; figlet -f dancingfont.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 73; figlet -f decimal.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 74; figlet -f defleppard.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 75; figlet -f diamond.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 76; figlet -f dietcola.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 77; figlet -f digital.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 78; figlet -f doh.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 79; figlet -f doom.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 80; figlet -f dosrebel.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 81; figlet -f dotmatrix.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 82; figlet -f double.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 83; figlet -f doubleshorts.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 84; figlet -f drpepper.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 85; figlet -f dwhistled.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 86; figlet -f eftichess.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 87; figlet -f eftifont.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 88; figlet -f eftipiti.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 89; figlet -f eftirobot.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 90; figlet -f eftitalic.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 91; figlet -f eftiwall.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 92; figlet -f eftiwater.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 93; figlet -f epic.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 94; figlet -f fender.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 95; figlet -f filter.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 96; figlet -f fire_font-k.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 97; figlet -f fire_font-s.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 98; figlet -f flipped.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 99; figlet -f flowerpower.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 100; figlet -f fourtops.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 101; figlet -f fraktur.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 102; figlet -f funface.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 103; figlet -f funfaces.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 104; figlet -f fuzzy.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 105; figlet -f georgi16.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 106; figlet -f Georgia11.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 107; figlet -f ghost.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 108; figlet -f ghoulish.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 109; figlet -f glenyn.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 110; figlet -f goofy.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 111; figlet -f gothic.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 112; figlet -f graceful.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 113; figlet -f gradient.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 114; figlet -f graffiti.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 115; figlet -f greek.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 116; figlet -f heart_left.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 117; figlet -f heart_right.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 118; figlet -f henry3d.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 119; figlet -f hex.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 120; figlet -f hieroglyphs.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 121; figlet -f hollywood.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 122; figlet -f horizontalleft.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 123; figlet -f horizontalright.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 124; figlet -f ICL-1900.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 125; figlet -f impossible.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 126; figlet -f invita.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 127; figlet -f isometric1.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 128; figlet -f isometric2.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 129; figlet -f isometric3.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 130; figlet -f isometric4.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 131; figlet -f italic.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 132; figlet -f ivrit.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 133; figlet -f jacky.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 134; figlet -f jazmine.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 135; figlet -f jerusalem.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 136; figlet -f katakana.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 137; figlet -f kban.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 138; figlet -f keyboard.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 139; figlet -f knob.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 140; figlet -f konto.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 141; figlet -f kontoslant.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 142; figlet -f larry3d.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 143; figlet -f lcd.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 144; figlet -f lean.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 145; figlet -f letters.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 146; figlet -f lildevil.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 147; figlet -f lineblocks.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 148; figlet -f linux.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 149; figlet -f lockergnome.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 150; figlet -f madrid.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 151; figlet -f marquee.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 152; figlet -f maxfour.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 153; figlet -f merlin1.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 154; figlet -f merlin2.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 155; figlet -f mike.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 156; figlet -f mini.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 157; figlet -f mirror.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 158; figlet -f mnemonic.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 159; figlet -f modular.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 160; figlet -f morse2.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 161; figlet -f morse.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 162; figlet -f moscow.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 163; figlet -f mshebrew210.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 164; figlet -f muzzle.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 165; figlet -f nancyj-fancy.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 166; figlet -f nancyj.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 167; figlet -f nancyj-improved.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 168; figlet -f nancyj-underlined.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 169; figlet -f nipples.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 170; figlet -f nscript.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 171; figlet -f ntgreek.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 172; figlet -f nvscript.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 173; figlet -f o8.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 174; figlet -f octal.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 175; figlet -f ogre.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 176; figlet -f oldbanner.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 177; figlet -f os2.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 178; figlet -f pawp.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 179; figlet -f peaks.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 180; figlet -f peaksslant.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 181; figlet -f pebbles.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 182; figlet -f pepper.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 183; figlet -f poison.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 184; figlet -f puffy.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 185; figlet -f puzzle.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 186; figlet -f pyramid.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 187; figlet -f rammstein.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 188; figlet -f rectangles.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 189; figlet -f red_phoenix.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 190; figlet -f relief2.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 191; figlet -f relief.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 192; figlet -f reverse.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 193; figlet -f roman.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 194; figlet -f rot13.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 195; figlet -f rotated.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 196; figlet -f rounded.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 197; figlet -f rowancap.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 198; figlet -f rozzo.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 199; figlet -f runic.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 200; figlet -f runyc.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 201; figlet -f santaclara.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 202; figlet -f sblood.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 203; figlet -f script.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 204; figlet -f serifcap.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 205; figlet -f shadow.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 206; figlet -f shimrod.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 207; figlet -f short.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 208; figlet -f slant.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 209; figlet -f slide.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 210; figlet -f slscript.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 211; figlet -f smallcaps.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 212; figlet -f small.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 213; figlet -f smisome1.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 214; figlet -f smkeyboard.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 215; figlet -f smpoison.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 216; figlet -f smscript.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 217; figlet -f smshadow.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 218; figlet -f smslant.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 219; figlet -f smtengwar.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 220; figlet -f soft.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 221; figlet -f speed.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 222; figlet -f spliff.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 223; figlet -f s-relief.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 224; figlet -f stacey.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 225; figlet -f stampate.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 226; figlet -f stampatello.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 227; figlet -f standard.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 228; figlet -f starstrips.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 229; figlet -f starwars.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 230; figlet -f stellar.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 231; figlet -f stforek.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 232; figlet -f stop.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 233; figlet -f straight.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 234; figlet -f sub-zero.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 235; figlet -f swampland.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 236; figlet -f swan.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 237; figlet -f sweet.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 238; figlet -f tanja.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 239; figlet -f tengwar.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 240; figlet -f term.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 241; figlet -f test1.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 242; figlet -f thick.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 243; figlet -f thin.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 244; figlet -f threepoint.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 245; figlet -f ticks.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 246; figlet -f ticksslant.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 247; figlet -f tiles.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 248; figlet -f tinker-toy.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 249; figlet -f tombstone.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 250; figlet -f train.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 251; figlet -f trek.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 252; figlet -f tsalagi.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 253; figlet -f tubular.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 254; figlet -f twisted.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 255; figlet -f twopoint.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 256; figlet -f univers.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 257; figlet -f usaflag.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 258; figlet -f varsity.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 259; figlet -f wavy.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 260; figlet -f weird.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 261; figlet -f wetletter.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 262; figlet -f whimsy.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 263; figlet -f wow.flf `date '+%d.%m.%Y %H:%M:%S'`
# SELECTION
echo 6; figlet -f 5lineoblique.flf `date '+%d.%m.%Y %H:%M:%S'`
echo 142; figlet -f greek.flf `date '+%d.%m.%Y %H:%M:%S'`
